import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { WagmiProvider } from "./components/WagmiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className + " p-8 pb-12 pt-28"}>
        <WagmiProvider>
        <Navbar />
        {children}
        <Footer />
        </WagmiProvider>
      </body>
    </html>
  )
}
